<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Приём граждан руководством БРКА");
?><span style="font-family: 'Times New Roman', Times; font-size: 16pt;">Председатель Белорусской республиканской коллегии адвокатов осуществляет прием в последний четверг каждого месяца с 9.00 до 13.00 по предварительной записи. <br>
 </span><span style="font-family: 'Times New Roman', Times; font-size: 16pt;">Предварительная запись осуществляется по телефону: 8(017) 2005534.<br>
 <span style="font-family: 'Times New Roman', Times; font-size: 16pt;"> </span><br>
 <span style="font-family: 'Times New Roman', Times; font-size: 16pt;">Заместитель председателя Белорусской республиканской коллегии адвокатов осуществляет прием каждый вторник с 9.00 до 13.00. </span><span style="font-family: 'Times New Roman', Times; font-size: 16pt;"> </span> <span style="font-family: Georgia, serif; font-size: 15pt; color: #7a0026;"><b><i><span style="color: #7a0045;"><br>
 </span></i></b></span><b><i><span style="color: #7a0045; font-family: 'Times New Roman', Times; font-size: 16pt;"><br>
 </span></i></b><b><i><span style="color: #7a0045; font-family: 'Times New Roman', Times; font-size: 16pt;">Внимание! </span><br>
 </i></b><b><i><b><i><span style="color: #7a0045;"><span style="font-family: 'Times New Roman', Times; font-size: 16pt;">Руководство Белорусской республиканской коллегии адвокатов осуществляет прием по вопросам деятельности адвокатуры и не оказывает юридическую помощь в виде устных консультаций. </span><br>
 </span></i></b><b><i><span style="font-family: 'Times New Roman', Times; font-size: 16pt;"><span style="color: #7a0045;">Для получения предварительного разъяснения норм законодательства по вопросам, не требующим ознакомления с документами, Вы можете воспользоваться помощью интернет-ресурса "Бесплатная юридическая онлайн-консультация Белорусской республиканской коллегии адвокатов" по адресу:<a href="https://www.rka.by/faq_ask/">https://www.rka.by/faq_ask/</a>.</span></span></i></b></i></b></span><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>