<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Преимущества оказания адвокатом юридической помощи субъеткам хозяйствования");
$APPLICATION->SetTitle("Юридическое обслуживание субъектов хозяйствования");
?><i><b><span style="font-family: Georgia, serif;"><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">Уважаемые субъекты хозяйствования!</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span></span></b></i><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
В случае, если в вашей деятельности юридические вопросы возникают нечасто, то оптимальным решением для вас будет заключение с адвокатом договора на оказание юридической помощи по&nbsp;</span><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">выполнению конкретного поручения</span></b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">. </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
В случае, если юридическая помощь вам необходима постоянно, то предлагаем рассмотреть такой вариант сотрудничества с адвокатом как </span><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">абонентское юридическое обслуживание</span></b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">. </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
Оба варианта имеют следующие преимущества для вашего бизнеса:</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- размер и порядок оплаты юридической помощи определяется по соглашению сторон;&nbsp;</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- оплата определяется сторонами договора за конкретный период либо за конкретно выполняемую работу;</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- исключаются расходы на уплату взносов в ФСЗН, подоходного налога, налога на добавленную стоимость;</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- отсутствует необходимость в организации адвокату рабочего места, в оплате социального пакета, информационных баз законодательства, расходных материалов и т.д.;</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- адвокаты обладают высоким уровнем&nbsp;квалификации, который подтверждается сдачей экзамена при получении лицензии, регулярной аттестацией, повышением квалификации на соответствующих курсах в Института переподготовки и повышения квалификации судей, работников прокуратуры, судов и учреждений юстиции Белорусского государственного университета;</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- адвокаты имеют опыт оказания юридической помощи по широкому кругу вопросов; - опыт ведения дел как в общих, так и в экономических судах, арбитражных и третейских судах; опыт медиативной деятельности (около половины адвокатов нашей республики имеют удостоверение медиатора);</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
- адвокатская тайна. Сведения о вопросах, по которым клиент обратился за юридической помощью, суть консультаций, разъяснений, справок, полученных клиентом от адвоката, сведения о личной жизни клиента, информация, полученная от клиента, об обстоятельствах совершения преступления по уголовному делу, по которому адвокат осуществлял защиту прав, свобод и интересов клиента, а также сведения, составляющие коммерческую тайну клиент, являются адвокатской тайной.&nbsp;Адвокат, стажеры и помощники адвоката не могут быть допрошены в качестве свидетелей об обстоятельствах, составляющих адвокатскую тайну, а государственные органы и иные организации не вправе истребовать, изымать и иным образом получать у адвоката, стажера и помощника адвоката информацию, составляющую адвокатскую тайну.</span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><br>
 <span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">
Адвокатов, которые специализируются на оказании юридической помощи субъектам хозяйствования, вы можете найти через поисковый запрос на странице </span><a href="https://rka.by/search_adv/"><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">https://rka.by/search_adv/</span></a><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 13pt;">, указав необходимую отрасль права (хозяйственное право, исполнительное производство, интеллектуальная собственность и т.д.).</span><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>