<?
$PERM["lokalnye-akty-brka"]["*"]="D";
$PERM["lokalnye-akty-brka"]["G1"]="X";
$PERM["test"]["*"]="D";
$PERM["test"]["7"]="X";
$PERM["forum-old"]["*"]="D";
$PERM["forum-old"]["G10"]="W";
$PERM["upload"]["10"]="U";
$PERM["bitrix"]["11"]="R";
$PERM["/"]["*"]="R";
$PERM["news"]["G11"]="W";
$PERM["reviews"]["*"]="D";
$PERM["reviews"]["G1"]="X";
?>