<?
$PERM["upload"]["10"]="U";
$PERM["bitrix"]["11"]="R";
$PERM["/"]["*"]="R";
$PERM["news"]["G11"]="W";
$PERM["reviews"]["*"]="D";
$PERM["reviews"]["G1"]="X";
$PERM["forum"]["*"]="D";
$PERM["forum"]["G10"]="W";
?>