<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Модерация отзывов");
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:forum", 
	"template", 
	array(
		"AJAX_POST" => "N",
		"ATTACH_MODE" => array(
			0 => "NAME",
		),
		"ATTACH_SIZE" => "",
		"CACHE_TIME" => "3600",
		"CACHE_TIME_FOR_FORUM_STAT" => "0",
		"CACHE_TIME_USER_STAT" => "0",
		"CACHE_TYPE" => "A",
		"PREORDER" => "N",
		"CHECK_CORRECT_TEMPLATES" => "N",
		"COMPONENT_TEMPLATE" => "template",
		"DATE_FORMAT" => "d.m.Y",
		"DATE_TIME_FORMAT" => "d.m.Y H:i:s",
		"EDITOR_CODE_DEFAULT" => "N",
		"FID" => array(
			0 => "11",
			1 => "12",
			2 => "13",
			3 => "14",
		),
		"FORUMS_PER_PAGE" => "15",
		"HELP_CONTENT" => "",
		"IMAGE_SIZE" => "500",
		"MESSAGES_PER_PAGE" => "10",
		"NAME_TEMPLATE" => "",
		"NO_WORD_LOGIC" => "N",
		"PAGE_NAVIGATION_TEMPLATE" => "",
		"PAGE_NAVIGATION_WINDOW" => "",
		"PATH_TO_AUTH_FORM" => "",
		"PATH_TO_ICON" => "/bitrix/images/forum/icon/",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"RATING_ID" => "",
		"RATING_TYPE" => "",
		"RESTART" => "N",
		"RSS_CACHE" => "undefined",
		"RSS_COUNT" => "30",
		"RSS_TN_DESCRIPTION" => "undefined",
		"RSS_TN_TITLE" => "undefined",
		"RSS_TYPE_RANGE" => array(
			0 => "undefined",
		),
		"RULES_CONTENT" => "",
		"SEF_MODE" => "N",
		"SEND_MAIL" => "E",
		"SEO_USER" => "Y",
		"SEO_USE_AN_EXTERNAL_SERVICE" => "N",
		"SET_DESCRIPTION" => "N",
		"SET_NAVIGATION" => "Y",
		"SET_PAGE_PROPERTY" => "N",
		"SET_TITLE" => "Y",
		"SHOW_AUTHOR_COLUMN" => "N",
		"SHOW_AUTH_FORM" => "N",
		"SHOW_FIRST_POST" => "N",
		"SHOW_FORUMS" => "N",
		"SHOW_FORUMS_LIST" => "N",
		"SHOW_FORUM_ANOTHER_SITE" => "N",
		"SHOW_FORUM_USERS" => "N",
		"SHOW_LEGEND" => "N",
		"SHOW_NAVIGATION" => "N",
		"SHOW_RATING" => "N",
		"SHOW_STATISTIC_BLOCK" => array(
		),
		"SHOW_SUBSCRIBE_LINK" => "N",
		"SHOW_TAGS" => "N",
		"SHOW_VOTE" => "N",
		"THEME" => "gray",
		"TIME_INTERVAL_FOR_USER_STAT" => "",
		"TMPLT_SHOW_ADDITIONAL_MARKER" => "",
		"TOPICS_PER_PAGE" => "10",
		"USER_FIELDS" => array(
		),
		"USER_PROPERTY" => array(
		),
		"USE_DESC_PAGE_MESSAGE" => "N",
		"USE_DESC_PAGE_TOPIC" => "Y",
		"USE_LIGHT_VIEW" => "N",
		"USE_NAME_TEMPLATE" => "N",
		"USE_RSS" => "N",
		"WORD_LENGTH" => "",
		"WORD_WRAP_CUT" => "",
		"VARIABLE_ALIASES" => array(
			"FID" => "FID",
			"TID" => "TID",
			"MID" => "MID",
			"UID" => "UID",
		)
	),
	false
);?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>