<b><i><span style="font-size: 14pt; font-family: &quot;Times New Roman&quot;, Times;"><span style="font-size: 16pt;">Уважаемые посетители!</span></span></i></b><br>
 В рамках бесплатной юридической онлайн-консультации адвокаты Республики Беларусь дают предварительное разъяснение норм законодательства Республики Беларусь по вопросам, не требующим ознакомления с документами и иными материалами.<br>
<br>
 Здесь Вы можете изучить текст <a href="/pravila-online-konsultacii/" rel="nofollow">Правил работы интернет-ресурса "Бесплатная юридическая онлайн-консультация Белорусской республиканской коллегии адвокатов".</a><br>
 <i><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt;"><span style="color: #7a0026;">&nbsp; <br>
 &nbsp;&nbsp;<i><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt;"><span style="color: #7a0045;">Внимание! </span><br>
 <span style="color: #7a0045;"> </span><span style="color: #7a0026;"><span style="color: #7a0045;"> </span><i><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt;"><span style="color: #7a0045;">&nbsp; Если Ваш вопрос не соответствует Правилам, рекомендуем обратиться на личный прием к адвокату.</span><br>
 <span style="color: #7a0045;"> </span><i><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt;"><span style="color: #7a0045;">&nbsp; Адвокаты отвечают на вопросы онлайн-консультации&nbsp;по мере возможности. </span><br>
 <span style="color: #7a0045;"> </span><b><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt; color: #7a0045;">&nbsp; Вопросы, содержащие личные данные, могут быть оставлены без ответа с целью неразглашения персональных данных.</span><br>
 <span style="color: #7a0045;"> </span><span style="font-family: &quot;Times New Roman&quot;, Times; font-size: 16pt;"><b><span style="color: #7a0045;">&nbsp; Вопросы, на которые даны ответы, хранятся в базе данных сайта в течение одного года, после чего удаляются.</span></b></span></b></span></b></i></span></b></i></span></span></b></i></span></span></b></i>